# Generated by Django 3.1.7 on 2021-04-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0008_auto_20210412_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProject',
        ),
    ]
