# Generated by Django 3.1.7 on 2021-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0010_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('place', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
