# Generated by Django 3.1.7 on 2021-04-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0011_auto_20210414_0720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
